class _BotCommands:
    def __init__(self):
        self.LeechCommand = 'leechlinks'
        self.gLeechCommand = 'ururdj'
        self.ExtractCommand = 'iididi9oo'
        self.gExtractCommand = 'ruruj3'
        self.ArchiveCommand = 'iddiir8'
        self.gArchiveCommand = 'ppiuhu8'
        self.telegramfleechCommand = 'dyruhr8'
        self.telegramexleechCommand = 'djdijdi8'
        self.gcloneCommand = 'jabran6'
        self.YtdlCommand = 'ytdl'
        self.gYtdlCommand = 'jabardasti5'
        self.PytdlCommand = 'maduhij6'
        self.gPytdlCommand = 'rjjrrj7'        
        self.ToggleDocCommand = 'toggledoc'
        self.ToggleVidCommand = 'togglevid'
        self.SaveCommand = 'savethumb'
        self.ClearCommand = 'clearthumb'
        self.RenameCommand = 'rename'
        self.StatusCommand = 'statustlx'
        self.SpeedCommand = 'speedtesttlx'
        self.HelpCommand = 'shanti'
        self.LogCommand = 'logshant'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
